### ISSUE TITLE
Can we update+simplify the opencv-python installation?

### ISSUE THREAD

**Issue by spencerahill** [DIYnamics/digipyro#6]
From the [opencv-python website](https://github.com/skvark/opencv-python), it looks like one can install everything via a simple `pip install`.  But our [installation script](https://github.com/DIYnamics/digipyro/blob/master/util/install.sh) has a much more involved script that is only valid for Mac.

@DJ-2805 do you know if the opencv-python build on pip will work?

**Comment by DJ-2805** [comment]
The Mac script was designed by Sam. I redid the SOP where it walks the user through installing the dependencies through pip. It should be in the README.

**Comment by spencerahill** [comment]
OK perfect.  So that means that installation script is obsolete and can be deleted, right?

**Comment by DJ-2805** [comment]
I would say so, I kept it in case initially, but I don't see myself using
it in the future.

**Comment by spencerahill** [comment]
Great, I'll remove as part of the broader package restructuring I've started in https://github.com/spencerahill/digipyro/tree/package-restructure.

Will keep this issue open until that's merged.

**Comment by spencerahill** [comment]
OK, #7 is now ready to merge.  Once it's in, I'll return to this restructuring.  So @DJ-2805 and anybody else, you might hold off on any big changes until I get that in.  Otherwise you'll probably end up with a bunch of merge conflicts that will be annoying to deal with manually.

**Comment by spencerahill** [comment]
Closed in #10
